environment: "production"

backend:
  replicas: 3

frontend:
  replicas: 3

image:
  backend:
    repository: ghcr.io/obisu/my-flask-app/backend
    tag: ""
  frontend:
    repository: ghcr.io/obisu/my-flask-app/frontend
    tag: ""
