environment: "default"

backend:
  replicas: 1

frontend:
  replicas: 1

image:
  backend:
    repository: ghcr.io/obisu/my-flask-app/backend
    tag: ""
  frontend:
    repository: ghcr.io/obisu/my-flask-app/frontend
    tag: ""

