name: CI - Frontend

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/ci-frontend.yaml"

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u obisu --password-stdin

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/obisu/my-flask-app/frontend:${{ github.sha }} frontend

      - name: Push frontend image
        run: |
          docker push ghcr.io/obisu/my-flask-app/frontend:${{ github.sha }}
